export const ENV = {
  TYPE: 'INPUT_TYPE',
  ACCESS_KEY: 'INPUT_SCW_ACCESS_KEY',
  CONTAINER_NAMESPACE_ID: 'INPUT_SCW_CONTAINERS_NAMESPACE_ID',
  CONTAINER_PORT: 'INPUT_SCW_CONTAINER_PORT',
  DNS: 'INPUT_SCW_DNS',
  DNS_PREFIX: 'INPUT_SCW_DNS_PREFIX',
  REGION: 'INPUT_SCW_REGION',
  REGISTRY: 'INPUT_SCW_REGISTRY',
  PROJECT_ID: 'INPUT_SCW_PROJECT_ID',
  SECRET_KEY: 'INPUT_SCW_SECRET_KEY',
  MEMORY_LIMIT: 'INPUT_SCW_MEMORY_LIMIT',
  MIN_SCALE: 'INPUT_SCW_MIN_SCALE',
  MAX_SCALE: 'INPUT_SCW_MAX_SCALE',
  MAX_CONCURRENCY: 'INPUT_SCW_MAX_CONCURRENCY',
  CPU_LIMIT: 'INPUT_SCW_CPU_LIMIT',
  SANDBOX: 'INPUT_SCW_SANDBOX',
  ROOT_ZONE: 'INPUT_ROOT_ZONE',
  ENVIRONMENT_VARIABLES: 'INPUT_SCW_ENVIRONMENT_VARIABLES',
  SECRETS: 'INPUT_SCW_SECRETS',
  CLEANUP_MAX_AGE_DAYS: 'INPUT_CLEANUP_MAX_AGE_DAYS',
  CLEANUP_DATE_FIELD: 'INPUT_CLEANUP_DATE_FIELD',
  CLEANUP_EXCLUDE_NAMES: 'INPUT_CLEANUP_EXCLUDE_NAMES',
  CLEANUP_DRY_RUN: 'INPUT_CLEANUP_DRY_RUN',
} as const

export const DEFAULTS = {
  DESCRIPTION: 'this container was created automatically by a github-action',
  PORT: 80,
  MIN_SCALE: 1,
  MAX_SCALE: 5,
  MAX_CONCURRENCY: 5,
  MEMORY_LIMIT: 256,
  CPU_LIMIT: 70,
  SANDBOX: 'v1',
  TIMEOUT_SECONDS: 60,
  REGION: 'fr-par',
  TYPE: 'deploy',
  CLEANUP_MAX_AGE_DAYS: 0,
  CLEANUP_DATE_FIELD: 'updated_at',
  CLEANUP_DRY_RUN: false,
} as const

export const TYPES = {
  DEPLOY: 'deploy',
  TEARDOWN: 'teardown',
  CLEANUP: 'cleanup',
} as const

export const CLEANUP_DATE_FIELDS = {
  CREATED_AT: 'created_at',
  UPDATED_AT: 'updated_at',
} as const

export const DNS = {
  CNAME: 'CNAME',
  ALIAS: 'ALIAS',
  TTL: 360,
  WAIT_TIMEOUT: 15 * 60 * 1000,
  RETRY_INTERVAL: 5 * 1000,
} as const

import { Containerv1 } from '@scaleway/sdk-container'

export const CONTAINER_NAME_MAX_LENGTH = Containerv1.ValidationRules.CreateContainerRequest.name.maxLength
export const HOSTNAME_MAX_LENGTH = 63
